# We should and could handle followings ourselves.

Metrics/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/GuardClause:
  Enabled: false

Layout/AlignHash:
  Enabled: false
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
